version: 2.1

jobs:
  check-node:
    docker:
      - image: cimg/node:24.3
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run:
          name: Node lifecycle check
          command: node dist/cli.js --warn-days=180 --cache-ttl=86400000

  audit-and-test:
    docker:
      - image: cimg/node:24.3
    steps:
      - checkout
      - run: npm ci
      - run:
          name: npm audit
          command: npm audit
      - run:
          name: npm test
          command: npm test

workflows:
  ci:
    jobs:
      - check-node
      - audit-and-test

  nightly:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only: main
    jobs:
      - check-node
      - audit-and-test
