version: 2.1

jobs:
  node-lifecycle-check:
    docker:
      - image: cimg/node:24.3
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run:
          name: Node lifecycle check
          command: node dist/cli.js --warn-days=180 --cache-ttl=86400000

  node-lifecycle-check-nightly:
    docker:
      - image: cimg/node:24.3
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run:
          name: Node lifecycle check
          command: node dist/cli.js --warn-days=180 --cache-ttl=0

  npm-audit:
    docker:
      - image: cimg/node:24.3
    steps:
      - checkout
      - run: npm ci
      - run:
          name: npm audit (all severities)
          command: npm audit

  npm-test:
    docker:
      - image: cimg/node:24.3
    steps:
      - checkout
      - run: npm ci
      - run: npm test

workflows:
  small-tasks:
    jobs:
      - node-lifecycle-check
      - npm-audit
      - npm-test

  nightly_checks:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only: main
    jobs:
      - node-lifecycle-check-nightly
      - npm-audit
      - npm-test
